open-pullrequest:
  only:
    - merge_request
  script:
    - RESPONCE_CHK = "False"
    - while [ RESPONCE_CHK = "False" ]
    - do
    -   'RESPONCE = curl -X POST -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${USER_TOKEN}" "https://api.github.com/repos/maruyaki/pipeline-migration-try-02/pulls" -d "{\"head\": \"${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}\", \"base\": \"${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}\", \"title\": \"${CI_MERGE_REQUEST_TITLE}\"}"'
    -   echo $RESPONCE > log.txt
    -   if [ `$RESPONCE | grep "Fail"` = "" ]; then RESPONCE_CHK = "True"; fi
    -   echo `$RESPONCE | grep "Fail"`
    - done
  artifacts:
    paths:
      - log.txt

