test-job:
  only:
    - merge_request
  script:
    - curl -X POST -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/maruyaki/
pipeline-migration-try-02/pulls -d '{"head":$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME,"base":$CI_MERGE_REQUEST_TARGET_BRANCH_NAME}'
